name: "Publish server image(release)"
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: ''
        description: 'The branch name should be like *-x.x.x, for example release-1.0.0'

jobs:
  build_latest:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: apache/hugegraph
      BRANCH: ${{inputs.branch}}

    steps:
    - name: Set image_url
      run: |
        image_url=hugegraph/hugegraph:$(echo "${{ inputs.branch }}" | grep -oP '(\d+\.\d+\.\d+)')
        echo $image_url && echo "image_url=$image_url" >> $GITHUB_ENV
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Checkout latest
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY_URL }}
        ref: ${{ env.BRANCH }}
        fetch-depth: 2

    - name: Build X86 Image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ env.image_url }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test X86 Image
      run: |
        echo "$image_url"
        docker images
        docker run -itd --name=graph -p 18080:8080 $image_url
        sleep 20s
        curl 0.0.0.0:18080 || exit
        docker ps -a
        sleep 20s
        curl 0.0.0.0:18080 || exit
        docker ps -a

    - name: Build ARM & Push all
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.image_url }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
